### ISSUE TITLE
Unable to Build Kubernetes Objects

### ISSUE THREAD

**Issue by asafii99** [kais271/pvc-exporter#27]
Hello,

I cannot install this helm chart, below is the error. 
My Kubernetes version is v1.17.11

![image](https://user-images.githubusercontent.com/58230087/162368931-5e7db75e-5c3c-4087-9875-70fe75838350.png)

My Kubernetes version is v1.17.11

**Comment by kais271** [comment]
Hi , it caused by you don't have prometheus installed.
You can try  add '--set serviceMonitor.enabled=false' to helm install.

**Comment by kais271** [comment]
Hi , it caused by you don't have prometheus installed.
You can try  add '--set serviceMonitor.enabled=false' to helm install.

**Comment by asafii99** [comment]
Hello, 

I have Prometheus installed on this cluster.

**Comment by kais271** [comment]
Cloud you please run `kubectl  api-resources|grep servicemonitor` ? Maybe the apiversion doesn't match.

**Comment by asafii99** [comment]
After running the command, I am getting no output

**Comment by kais271** [comment]
ok, which version of prometheus are you using?  run `kubectl  api-resources|grep monitoring` to check apiversion

**Comment by kais271** [comment]
`kubectl  get prometheus -A` to get prometheus version

**Comment by asafii99** [comment]
When I run these commands, I get no output, here is the info on the prometheus webpage

![image](https://user-images.githubusercontent.com/58230087/162446934-ba57a9b9-9ba5-42b4-a591-dedaea6f53b8.png)

**Comment by kais271** [comment]
Are you using native k8s and prometheus? It's weird if you have the Prometheus deployed within the cluster, but no CRD.

**Comment by asafii99** [comment]
I believe I am, here is my prometheus deployment configuration 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-deployment
  namespace: monitoring
  labels:
    app: prometheus-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      initContainers:
      - name: prometheus-data-permission-fix
        image: busybox
        command:
         - /bin/chmod
         - '-R'
         - '777'
         - /prometheus/
        volumeMounts:
         - name: prometheus-storage-volume
           mountPath: /prometheus/
      containers:
        - name: prometheus
          image: prom/prometheus
          args:
            - "--storage.tsdb.retention.time=12h"
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          resources:
            requests:
              cpu: 500m
              memory: 500M
            limits:
              cpu: 1
              memory: 1Gi
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
        - name: prometheus-storage-volume
          persistentVolumeClaim:
               claimName: prometheus-pvc
```
